mixed-port: 7890
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
global-client-fingerprint: chrome
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
mode: rule
log-level: error ## silent/error/warning/info/debug
ipv6: true
external-controller: 127.0.0.1:9090
profile:
  store-selected: false ## It's better to default to "auto" every time it restarts.
  store-fake-ip: true
  tracing: false
sniffer:
  enable: true
  sniffing:
  - http
  - tls

tun:
  enable: true
  stack: system # or gvisor 
  dns-hijack:
  - any:53
  - tcp://any:53
  auto-redir: true
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  #listen: 127.0.0.1:53 ## Or 0.0.0.0:53 for LAN.
  ipv6: true
  prefer-h3: true
  default-nameserver:
  - 127.0.0.1
  - 1.1.1.1
  - 8.8.8.8
  - 217.218.155.155
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
  - 127.0.0.1
  - 217.218.155.155
  - 8.8.8.8
  - 1.1.1.1
  fake-ip-filter:
  - '*.lan'
  - stun.*.*.*
  - stun.*.*
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - '*.openwrt.pool.ntp.org'
  - pool.ntp.org
  - ntp.ubuntu.com
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - api.joox.com
  - joox.com
  - '*.xiami.com'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - +.xboxlive.com
  - '*.*.stun.playstation.net'
  - xbox.*.*.microsoft.com
  - '*.ipv6.microsoft.com'
  - speedtest.cros.wr.pvp.net
  fallback:
  - 1.0.0.1
  - 8.8.4.4
  fallback-filter:
    geoip: true
    geoip-code: IR
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/3
    - 240.0.0.0/4
    - ::1/128
    - 64:ff9b:1::/48
    - fc00::/7
    - fe80::/10
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    - +.gvt1.com
    - +.twitter.com
    - +.bing.com
proxies:
- {name: 